version: '3.1'
services:
  stats-server:
    build:
      context: ./statistics/stats-service
      dockerfile: Dockerfile
    image: statistics_server_image
    container_name: statistics_server_container
    restart: on-failure
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/statisticsDB

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db_container
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: statisticsDB
      POSTGRES_USER: ewmuser
      POSTGRES_PASSWORD: postgres

  ewm-service:
    build: ./ewm-service
    image: ewm_service_image
    container_name: ewm_service_container
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      EWM_STAT_SERVER_URL: http://stats-server:9090/
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/serviceDB

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db_container
    ports:
      - "6540:5432"
    environment:
      POSTGRES_DB: serviceDB
      POSTGRES_USER: ewmuser
      POSTGRES_PASSWORD: postgres
